// Generated by https?://quicktype.io

export interface IWPosts {
    context?: 'view' | 'embed' | 'edit';
    page?: number;
    per_page?: number;
    search?: string;
    after?: Date;
    author?: number;
    author_exclude?: number;
    before?: Date;
    exclude?: number;
    include?: number;
    offset?: number;
    order?: 'asc' | 'desc';
    orderby?: string;
    slug?: string;
    status?: string;
    categories?: number;
    categories_exclude?: number;
    tags?: Array<string>;
    tags_exclude?: Array<string>;
    sticky?: boolean;

}
export interface IWPages extends IWPosts {
    parent?: number;
    parent_exclude?: number;
}
export interface IWMedia extends IWPosts {
    media_type?: 'image' | 'video' | 'text' | 'application' | 'audio';
    mime_type?: string;
}
