// Generated by https?://quicktype.io

export interface IWPublishPosts {
    title?: string;
    content?: string;
    date?: Date;
    date_gmt?: string;
    author?: number;
    password?: string;
    excerpt?: string;
    featured_media?: number;
    comment_status?: 'open'|'closed';
    ping_status?: 'open'|'closed';
    order?: 'asc' | 'desc';
    orderby?: string;
    slug?: string;
    status?: string;
    categories?: number;
    categories_exclude?: number;
    tags?: Array<string>;
    tags_exclude?: Array<string>;
    sticky?: boolean;

}
